# -*- coding: utf-8 -*-
"""Test Maker RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Upi3dG73tz15y9xfKqqHn5Vcw3Me5pq6

# 🎓 Course Material RAG Chatbot (100% Free)

Answers questions from your **PDFs, R scripts, and Excel files** using:
- 🤖 **Gemini 2.0 Flash** — free via [Google AI Studio](https://aistudio.google.com)
- 🔍 **HuggingFace Embeddings** — free, runs locally in Colab
- 🗄️ **ChromaDB** — free, runs locally in Colab

---
### ✅ How to get your free Gemini API key:
1. Go to **[aistudio.google.com](https://aistudio.google.com)**
2. Click **Get API Key → Create API key**
3. Copy it and paste below in Step 3

## Step 1: Install Dependencies
"""

!pip install -q docling langchain langchain-community langchain-google-genai \
    sentence-transformers chromadb langchain-text-splitters \
    pandas openpyxl tabulate pypdf
!apt-get install -q poppler-utils
print('✅ All packages installed!')

"""## Step 2: Mount Google Drive"""

from google.colab import drive
drive.mount('/content/drive')
print('✅ Drive mounted!')

"""## Step 3: Set API Key & Course Folder Path

**Tip:** Use Colab Secrets (🔑 icon in left sidebar) and add a secret named `GOOGLE_API_KEY` — safer than pasting it directly.
"""

import os

# Load from Colab Secrets (recommended)
try:
    from google.colab import userdata
    os.environ["OPENAI_API_KEY"] = userdata.get("OPEN_AI_API_KEY")
    print("✅ OpenAI API key loaded from Colab Secrets")
except Exception:
    # Fallback: paste directly ONLY if needed
    os.environ["OPENAI_API_KEY"] = "PASTE_YOUR_OPENAI_API_KEY_HERE"  # <-- CHANGE IF NEEDED
    print("⚠️ Using manually pasted OpenAI key")

# Path to the folder in your Google Drive with course files
COURSE_FOLDER = "/content/drive/MyDrive/Spring/Gen AI/Gen AI I Project/Materials"  # <-- keep or change if needed

print(f"📁 Course folder: {COURSE_FOLDER}")

"""## Step 4: Process Course Files (PDFs, R scripts, Excel, CSV)"""

import os
import pandas as pd
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document


def infer_document_type(file_name):
    file_lower = file_name.lower()

    if file_lower.endswith(".r"):
        return "code"
    elif file_lower.endswith(".csv") or file_lower.endswith(".xlsx") or file_lower.endswith(".xls"):
        return "tabular_data"
    elif "slides" in file_lower:
        return "slides"
    else:
        return "notes"


def process_course_materials(directory_path):
    # Try Docling first (best for PDFs with images/tables)
    try:
        from docling.document_converter import DocumentConverter
        converter = DocumentConverter()
        use_docling = True
        print("📄 Using Docling for PDF extraction (best quality)")
    except Exception:
        use_docling = False
        print("📄 Using pypdf for PDF extraction (fallback)")

    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=150,
        separators=["\n\n", "\n", " ", ""]
    )

    supported = (".pdf", ".r", ".xlsx", ".xls", ".csv")
    all_files = [f for f in os.listdir(directory_path) if f.lower().endswith(supported)]

    if not all_files:
        print(f"⚠️ No supported files found in: {directory_path}")
        print(f"Files present: {os.listdir(directory_path)}")
        return []

    print(f"\n📂 Found {len(all_files)} file(s): {all_files}\n")
    all_docs = []

    for file in all_files:
        file_path = os.path.join(directory_path, file)
        text = ""

        try:
            ext = file.lower().rsplit(".", 1)[-1]
            document_type = infer_document_type(file)

            if ext == "pdf":
                if use_docling:
                    result = converter.convert(file_path)
                    text = result.document.export_to_markdown()
                else:
                    from pypdf import PdfReader
                    reader = PdfReader(file_path)
                    text = "\n\n".join(p.extract_text() or "" for p in reader.pages)

            elif ext == "r":
                with open(file_path, "r", encoding="utf-8", errors="replace") as f:
                    raw_code = f.read()
                    text = (
                        f"Document type: R code\n"
                        f"Source file: {file}\n"
                        f"This file contains R code, functions, scripts, or implementation examples.\n\n"
                        f"{raw_code}"
                    )

            elif ext in ("xlsx", "xls"):
                df_dict = pd.read_excel(file_path, sheet_name=None)
                excel_chunks = []

                for sheet_name, df in df_dict.items():
                    sheet_text = (
                        f"Document type: spreadsheet\n"
                        f"Source file: {file}\n"
                        f"Sheet name: {sheet_name}\n"
                        f"This sheet contains tabular data, numerical values, or examples.\n\n"
                        f"{df.to_string(index=False)}"
                    )
                    excel_chunks.append((sheet_name, sheet_text))

            elif ext == "csv":
                df = pd.read_csv(file_path)
                text = (
                    f"Document type: csv table\n"
                    f"Source file: {file}\n"
                    f"This file contains tabular data, numerical values, or dataset examples.\n\n"
                    f"{df.to_string(index=False)}"
                )

            # Handle Excel separately so each sheet becomes its own source block
            if ext in ("xlsx", "xls"):
                for sheet_name, sheet_text in excel_chunks:
                    if not sheet_text.strip():
                        continue

                    sheet_text = sheet_text.replace("\n\n\n", "\n\n").replace("  ", " ")
                    chunks = text_splitter.split_text(sheet_text)

                    for i, chunk in enumerate(chunks):
                        all_docs.append(
                            Document(
                                page_content=chunk,
                                metadata={
                                    "source": file,
                                    "document_type": document_type,
                                    "file_extension": ext,
                                    "sheet_name": sheet_name,
                                    "chunk_id": i,
                                    "total_chunks": len(chunks)
                                }
                            )
                        )

                    print(f"  ✅ {file} | sheet={sheet_name}: {len(chunks)} chunk(s)")

                continue

            if not text.strip():
                print(f"  ⚠️ {file}: empty after extraction, skipping")
                continue

            text = text.replace("\n\n\n", "\n\n").replace("  ", " ")
            chunks = text_splitter.split_text(text)

            for i, chunk in enumerate(chunks):
                all_docs.append(
                    Document(
                        page_content=chunk,
                        metadata={
                            "source": file,
                            "document_type": document_type,
                            "file_extension": ext,
                            "sheet_name": None,
                            "chunk_id": i,
                            "total_chunks": len(chunks)
                        }
                    )
                )

            print(f"  ✅ {file}: {len(chunks)} chunk(s)")

        except Exception as e:
            print(f"  ❌ {file}: Error — {e}")

    print(f"\n📊 Total chunks ready for indexing: {len(all_docs)}")
    return all_docs


docs = process_course_materials(COURSE_FOLDER)

"""## Step 5: Build Vector Store (free local embeddings + ChromaDB)"""

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

if not docs:
    raise ValueError('No documents found. Fix your COURSE_FOLDER path and re-run Step 4.')

print('🔄 Loading embedding model (may take ~1 min on first run)...')

# Runs entirely locally — no API key or cost needed
embeddings = HuggingFaceEmbeddings(
    model_name='all-MiniLM-L6-v2',
    model_kwargs={'device': 'cpu'},
    encode_kwargs={'normalize_embeddings': True}
)

print('✅ Embeddings loaded. Indexing documents...')

vectorstore = Chroma.from_documents(
    documents=docs,
    embedding=embeddings,
    persist_directory='/content/chroma_db'
)

print(f'✅ Vector store built! {vectorstore._collection.count()} vectors indexed.')

"""## Step 6: Set Up Open AI gpt API


"""

!pip install -q langchain-openai openai
!pip install -q sentence-transformers

def rerank_documents(query, docs, top_k=4):

    pairs = [[query, doc.page_content] for doc in docs]

    scores = reranker.predict(pairs)

    ranked = sorted(
        zip(scores, docs),
        key=lambda x: x[0],
        reverse=True
    )

    top_docs = [doc for _, doc in ranked[:top_k]]

    return top_docs

from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from sentence_transformers import CrossEncoder

# cross-encoder reranker model
reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

# OpenAI model
llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0.2,
    api_key=os.environ.get("OPENAI_API_KEY")
)

prompt_template = PromptTemplate.from_template("""
You are a test maker chatbot for a university course.

Use ONLY the retrieved course materials below to answer the request.
Do NOT use external knowledge.
Be clear and concise.
If the answer is not in the context, say: "I couldn't find that in the course materials."

When generating answers or questions:
Base them strictly on the context.

If the user asks for practice questions, a quiz, or a mini test:
Generate the requested number of questions.
Include both multiple choice and open-ended questions when possible.
After all questions, provide an Answer Key section.
For multiple choice questions, provide the correct letter and the text.
For open-ended questions, provide a short model answer.

At the end of every response, include a section exactly called:
Sources:
and list the source files you used.

Context:
--------
{context}
--------

Question: {question}

Answer:
""")

retriever = vectorstore.as_retriever(search_kwargs={"k": 10})

def rerank_documents(query, docs, top_k=4):
    pairs = [[query, doc.page_content] for doc in docs]
    scores = reranker.predict(pairs)

    ranked = sorted(
        zip(scores, docs),
        key=lambda x: x[0],
        reverse=True
    )

    top_docs = [doc for _, doc in ranked[:top_k]]
    return top_docs

def format_docs(query):
    docs = retriever.invoke(query)
    docs = rerank_documents(query, docs, top_k=4)

    formatted = []
    for doc in docs:
        source = doc.metadata.get("source", "unknown")
        doc_type = doc.metadata.get("document_type", "unknown")
        sheet_name = doc.metadata.get("sheet_name", None)

        header = f"[Source: {source} | Type: {doc_type}"
        if sheet_name not in [None, "None", "unknown"]:
            header += f" | Sheet: {sheet_name}"
        header += "]"

        formatted.append(f"{header}\n{doc.page_content}")

    return "\n\n".join(formatted)

qa_chain = (
    {"context": format_docs, "question": RunnablePassthrough()}
    | prompt_template
    | llm
    | StrOutputParser()
)

print("✅ Chatbot ready with OpenAI + reranker!")

llm.invoke("Explain PCA in one sentence")

answer = qa_chain.invoke("What is PCA?")
print(answer)

"""## Step 7: Chat with Your Course Materials!"""

def ask_bot():
    print("\n🎓 Test Maker Chatbot active!")
    print('Ask for a concept explanation, a practice question, or a mini test.')
    print('Type "exit" to stop.\n')

    while True:
        query = input("Your request: ").strip()

        if not query:
            continue

        if query.lower() in ("exit", "quit"):
            print("👋 Goodbye!")
            break

        try:
            answer = qa_chain.invoke(query)
            print(f"\n🤖 Response:\n{answer}")
            print("\n" + "-" * 60)

        except Exception as e:
            print(f"\n❌ Error: {e}\n")

ask_bot()

def ask_bot():
    print("\n🎓 Test Maker Chatbot active!")
    print('Ask for a concept explanation, a practice question, or a mini test.')
    print('Type "exit" to stop.\n')

    while True:
        query = input("Your request: ").strip()

        if not query:
            continue

        if query.lower() in ("exit", "quit"):
            print("👋 Goodbye!")
            break

        try:
            answer = qa_chain.invoke(query)
            print(f"\n🤖 Response:\n{answer}")
            print("\n" + "-" * 60)

        except Exception as e:
            print(f"\n❌ Error: {e}\n")

ask_bot()

"""## (Optional) Ask a Single Question
Useful for quick testing without the interactive loop.
"""

def ask(question):
    result = qa_chain.invoke(question)
    print(f"Q: {question}\n")
    print(f"A: {result}\n")

# Try it out:
ask("What is PCA and how does it work?")